//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DZ_DBBooks_EF_DatabeseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public int Id { get; set; }
        public int AuthorsID { get; set; }
        public string Tittle { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
